window.PokemonTypes = {
  bug: "bug",
  dark: "dark",
  dragon: "dragon",
  electric: "electric",
  fairy: "fairy",
  fighting: "fighting",
  fire: "fire",
  flying: "flying",
  ghost: "ghost",
  grass: "grass",
  ground: "ground",
  ice: "ice",
  normal: "normal",
  poison: "poison",
  psychic: "psychic",
  rock: "rock",
  steel: "steel",
  water: "water",
};

window.Pokemons = {
  bulbasaur: {
    id: "001",
    name: "Bulbasaur",
    type: window.PokemonTypes.grass,
    src: "assets/battle/pokes/bulbasaur.png",
    icon: "assets/icons/pokes/bulbasaur.png",
    actions: ["tackle"],
  },
  charmander: {
    id: "004",
    name: "Charmander",
    type: window.PokemonTypes.fire,
    src: "assets/battle/pokes/charmander.png",
    icon: "assets/icons/pokes/charmander.png",
    actions: ["tackle"],
  },
  dragonite: {
    id: "149",
    name: "Dragonite",
    type: window.PokemonTypes.dragon,
    src: "assets/battle/pokes/dragonite.png",
    icon: "assets/icons/pokes/dragonite.png",
    actions: ["tackle"],
  },
};
